### ISSUE TITLE
F# - Oracle Connection

### ISSUE THREAD

**Issue by philsivyer** [fsprojects/SQLProvider#110]
Hi
 Problem when trying to connect to ORACLE.
 I get error message "'FSharp.Data.Sql.SqlTypeProvider' reported an error: Exception has been thrown by the target of an invocation."

 My code is:
 #r @"C:\Users\Documents\Visual Studio 2013\Projects\Library2\packages\SQLProvider.0.0.9-alpha\lib\net40\FSharp.Data.SqlProvider.dll"

open System
 open System.Linq
 open FSharp.Data.Sql

// create a type alias with the connection string and database vendor settings
 type sql = SqlDataProvider< 
 ConnectionString = @"Data Source=gdev;Initial Catalog=test001;Integrated Security=True",
 DatabaseVendor = Common.DatabaseProviderTypes.ORACLE,
 ResolutionPath = @"C:\Users\Downloads\ODP.NET_Managed121020\odp.net\managed\common",
 IndividualsAmount = 1000,
 UseOptionTypes = true >
 let ctx = sql.GetDataContext()

**Comment by colinbull** [comment]
@philsivyer I'll have a look at this tommorrow, more depth. However at a cursory glance, I have some pointers that might help you out. 

* The connection string looks more like a SQL Server connection string rather than an Oracle one. I only say this because I don't think that the initial catalog is supported. See [here](http://docs.oracle.com/html/E10927_01/featConnecting.htm#i1006259)

* Try moving the resolution path to literal variable. I have has problems in the past with `@` not behaving as it should inline.

          let [<Literal>] resolutionPath = @"C:\Users\Downloads\ODP.NET_Managed121020\odp.net\managed\common"

Do you have a schema you can share? I don't need any data, just the DDL to re-create if thats possible, this will help me if the above pointers don't work out. 

Let me know how you get on

Cheers

**Comment by philsivyer** [comment]
Hi Colin
Made a couple of changes - see below and getting new error.
 
Regards
Phil
 
#r @"C:\Users\documents\visual studio 2013\Projects\Library2\packages\SQLProvider.0.0.9-alpha\lib\net40\FSharp.Data.SqlProvider.dll" open Systemopen System.Linqopen FSharp.Data.Sql let [<Literal>] ResolutionPath1 = @"C:\Users\Downloads\ODP.NET_Managed121020\odp.net\managed\common"// create a type alias with the connection string and database vendor settingstype sql = SqlDataProvider<               ConnectionString  = @"Data Source=PMLBSGDEV:1521/DATA001;User Id=crystal;Password=crystal",              ResolutionPath    = ResolutionPath1,              DatabaseVendor    = Common.DatabaseProviderTypes.ORACLE,              IndividualsAmount = 1000,              UseOptionTypes    = true >let ctx = sql.GetDataContext() ERROR NOW IS:“The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: ORA-00303: Network Library: Name-Value syntax error”
 Date: Wed, 28 Jan 2015 11:48:41 -0800

**Comment by colinbull** [comment]
Ahhh, O.K this can be because of a number of reasons.

* You have no `tnsnames.ora` setup because you haven't got the oracle client installed. This isn't required but it then means you have to setup the datasources in your app.config file as described on the oracle knowledge base. See the link at the end (1)

* You are not pointing the odp.net configuration to the `tnsnames.ora` file in your `app.config`. Again see the oracle knowledge base article.

* You have tnsnames setup, but the `SQLNet.ora` file isn't using TNSNAMES. It should look something like this. 

     names.directory_path = (TNSNAMES, HOSTNAME)

However this is going to depend on how oracle is deployed in your organisation. 

If it is none of these you can always fall back to not using tnsnames or the client at all and use the full oracle connection string. Something like this. 

     SERVER=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=MyHost)(PORT=MyPort))(CONNECT_DATA=(SERVICE_NAME=MyOracleSID)));uid=myUsername;pwd=myPassword; 

which is pretty epic, as far as connection strings go. 

(1) [Oracle Knowledge Base](https://docs.oracle.com/html/E41125_02/featConfig.htm)

**Comment by philsivyer** [comment]
Colin
First of all - is the syntax correct re "Literal - ResolutionPath"?
I do have TNS names set up as I use Toad and Crystal Reports.
 
Below is some test code that worked connecting to Oracle but not using LINQ.
#light #r @"System.Data.OracleClient.dll";; (* Import managed assemblies *)open Systemopen System.Dataopen System.Data.Commonopen System.Data.OracleClientopen System.Collectionsopen System.Textopen System.Windows.Forms let form =  let f = new Form()  f.Visible <- true      f.TopMost <- true      f.Text <- "TEST"       f.Height <- 600     f.Width <- 800      f    let grid =      let g = new DataGrid()      g.Dock <- DockStyle.Fill      g    form.Controls.Add(grid)   let connection_string = "Server=DFGHJ:112/AF007;Uid=crystal;Pwd=crystal;" let sql = "SELECT            APPROVAL_STATUS,            CASE WHEN APPROVAL_STATUS = 'APPROVED' THEN 'TEST1' ELSE 'TEST2' END AS TESTER,            PORTFOLIO_NAME            FROM MIS_TABLE1            WHERE ROWNUM<=100"  let data_table = new Data.DataTable()   try      let connection = new OracleClient.OracleConnection(connection_string)      let command = new OracleClient.OracleCommand (sql, connection)      let adapter = new OracleDataAdapter(command)      let r = adapter.Fill(data_table)      connection.Close()   with        | :? System.InvalidOperationException as ex ->      ignore(MessageBox.Show(ex.Message))    | _ ->      ignore(MessageBox.Show("Unknown Exception")) grid.DataSource <- data_table    do Application.Run(form)
 Date: Thu, 29 Jan 2015 01:39:04 -0800

**Comment by colinbull** [comment]
Yep the literal stuff looks correct. 

I notice that the code you use isn't using the managed client, it is using the native one. If you change the `resolutionPath` to point to the native client does it work then?

**Comment by philsivyer** [comment]
Colin
My changes - now with different error......
 
#r @"C:\Users\psivyer\documents\visual studio 2013\Projects\Library2\packages\SQLProvider.0.0.9-alpha\lib\net40\FSharp.Data.SqlProvider.dll"#r @"System.Data.OracleClient.dll"open Systemopen System.Linqopen FSharp.Data.Sql let [<Literal>] ResolutionPath1 = @"C:\Users\psivyer\Documents\Visual Studio 2013\Projects\Library2\packages\odp.net.managed.121.1.2\lib\net40"//let [<Literal>] ConnectionString1 = "Server=DEV:1521/001;Uid=welcome;Pwd=welcome;"  let [<Literal>] ConnectionString1 = "SERVER=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dev)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=001)));uid=welcome;pwd=welcome;"  // create a type alias with the connection string and database vendor settingstype sql = SqlDataProvider<              ConnectionString  = ConnectionString1,              ResolutionPath    = ResolutionPath1,              DatabaseVendor    = Common.DatabaseProviderTypes.ORACLE,              IndividualsAmount = 1000,              UseOptionTypes    = true >let ctx = sql.GetDataContext()
 Error: error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Exception has been thrown by the target of an invocation RegardsDate: Thu, 29 Jan 2015 02:28:34 -0800

**Comment by colinbull** [comment]
@philsivyer  Did you try using the unmanaged client? That example still seems to be using the managed one.

**Comment by philsivyer** [comment]
Colin
Excuse my ignorance here - is this something I need to download?
Regards
 
Date: Thu, 29 Jan 2015 06:00:46 -0800

**Comment by colinbull** [comment]
No, you actually already use it in the non linq example you sent me earlier. Basically all you need to do is point the resolution path at the `Oracle.DataAccess.Client.dll` rather than the `Oracle.ManagedDataAccess.Client`. On my install the unmanaged client is located in  `C:\Program Files\Oracle\product\11.2.0\client_1\ODP.NET\bin\4` but this will vary depending on the oracle version installed. So on my machine the resolution path will look something like this 

     let [<Literal>] resolutionPath = @"C:\Program Files\Oracle\product\11.2.0\client_1\ODP.NET\bin\4"

**Note** if you are using this in a console application / windows service rather than a script then including a reference to the dll in the project and setting copy local should be enough to get it working. You only really need to use the resolution path if you are using it from an *.fsx file.

**Comment by philsivyer** [comment]
Colin
I found the correct path to unmanaged as per your guide - unfortunately same error.
My code is in *.fsx file
 
Regards
 
Date: Thu, 29 Jan 2015 07:01:27 -0800

**Comment by colinbull** [comment]
In that case then can you share a schema and the script file?

**Comment by philsivyer** [comment]
I'm back in the office tomorrow and try to get this sent.
Thanks
 
Date: Thu, 29 Jan 2015 07:20:48 -0800

**Comment by philsivyer** [comment]
Colin
Can't send the schema - anyway it's huge.
Still hitting brick walls - you can see in my commented out code the variables I have tried and I know the connection strings are correct.
Below is the full script..

#r "Oracle.DataAccess"
#r @"C:\Users\documents\visual studio 2013\Projects\Library2\packages\SQLProvider.0.0.9-alpha\lib\net40\FSharp.Data.SqlProvider.dll"
#r @"System.Data.OracleClient.dll"
#r @"c:\users\documents\visual studio 2013\Projects\Library3\packages\SQLProvider.0.0.9-alpha\lib\net40\FSharp.Data.SqlProvider.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Data.Linq.dll"
#r @"c:\users\visual studio 2013\Projects\Library3\packages\FSharp.Data.TypeProviders.0.0.1\lib\net40\FSharp.Data.TypeProviders.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Data.dll"

open System
open System.Linq
open FSharp.Data.Sql
open System
open Microsoft.FSharp.Data.TypeProviders
//open System.Data.Linq.SqlClient
open System.Linq
open Microsoft.FSharp.Linq

//let [<Literal>] ResolutionPath1 = @"C:\Users\Documents\Visual Studio 2013\Projects\Library2\packages\odp.net.managed.121.1.2\lib\net40"
//let [<Literal>] ResolutionPath1 = @"C:\Users\Documents\Visual Studio 2013\Projects\Library2\Library2\bin\Debug"
//let [<Literal>] ResolutionPath1 = @"C:\Users\documents\visual studio 2013\Projects\Library2\Library2\packages.config"
let [<Literal>] ResolutionPath1 = @"C:\Users\Downloads\ODP.NET_Managed121020\odp.net\managed\x86"
//let [<Literal>] ResolutionPath1 = @"C:\Oracle\product\11.2.0\client_1\odp.net\bin\2.x"

//let [<Literal>] ConnectionString1 = "Server=ofred05\dba001;Uid=welcome;Pwd=welcome;"  
//let [<Literal>] ConnectionString1 = "User Id=crystal;password=crystal;Server=ofred05;Direct=True;Sid=dba001;Persist Security Info=True"
let [<Literal>] ConnectionString1 = "Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ofred05)(PORT=1521))(CONNECT_D‌​ATA=(SERVICE_NAME=dba001)));User ID=welcome;Password=welcome;"
// create a type alias with the connection string and database vendor settings


type sql = SqlDataProvider<                             
              ConnectionString  = ConnectionString1,
              ResolutionPath    = ResolutionPath1,
              DatabaseVendor    = Common.DatabaseProviderTypes.ORACLE,
              IndividualsAmount = 1000,
              UseOptionTypes    = true >

let ctx = sql.GetDataContext()

**Comment by colinbull** [comment]
Without seeing the schema, or at least a minimal repro, this is gonna be a tough one for me to fix. I'd be interested to know if it works against a very simple database, in your org. There are some scripts [here](https://github.com/fsprojects/SQLProvider/tree/master/src/DatabaseScripts/Oracle) that will create a sample schema for you to connect to, if you get chance. Try this and let me know the results.

**Comment by philsivyer** [comment]
Thanks
