### ISSUE TITLE
Support for Stored Procedures

### ISSUE THREAD

**Issue by drcrook1** [fsprojects/SQLProvider#130]
Ability to use stored procedures.  Or documentation on calling stored procedures.

I am attempting to use this in a production environment and I have complex queries that are taking in excess of 5 minutes.  Yes, minutes.  One such query takes 9 minutes.  Moving down to a stored procedure might work better.

**Comment by pezipink** [comment]
You can use (basic) stored procedures with all the provider types, though MySQL is not tested too well.  The procedures have to be basic though, as there is generally no way of getting metadata about the return columns, so the TP will just execute the proc with shcema only mode and some default arguments, and use the results to infer the response type.  There are also some other bits that are not supported with sprocs.

To use stored procs, simply navigate from the data context object to the ``stored procedures`` property, and find the proc you are interested in calling.

However, it would be interesting to know more about your problem;

* What database are you using?
* How complex is the query you are running and how are you writing it?
* Is the problem that the SQL provider is generating terrible SQL? Do you have adequate keys / indexes and so on to ensure and efficient query?  If you write the query yourself, does it perform a massive amount faster? 

It's quite possible the SQL provider is not generating brilliant SQL for a very complex query, it does not presently have an optimiser in its compilation pipeline and as such is not great at generating optimal SQL for very complex queries.  There is another SQL type provider that lets you specify exactly what SQL you would like to execute, see the SQL Client type provider - that might be a better fit depending on what you are trying to do.  

Cheers

Ross

**Comment by drcrook1** [comment]
Hi Ross,

 

I’m using SQL Azure

Query:

            let foodTruck = foodTruckRepository.Get(id).SuccessValue

            let attendances = attendanceRepository.GetAllForFoodTruck(id).SuccessValue

 

Broken down into:

                let foodTruck = query {for ft in context.``[DBO].[FOODTRUCK]`` do

                                                    where (ft.ID = id)

                                                    select ft}

                                                |> Seq.head

                                                |> convertSqlFoodTruck

 

                let attendances = query {for sa in context.``[DBO].[ATTENDANCE]`` do

                                                    where (sa.FOODTRUCKID = id)

                                                    select sa}

                                                |> Seq.map(fun sa -> convertSqlAttendance(sa).SuccessValue)

                                                |> Seq.toList

 

 

Joins as you can see are currently happening Web Server side (want to move that down to SQL preferably)  The attendances one is what takes forever though.  Getting the foodtruck itself takes < 1 second, but the second one is super slow.  Anything that needs that call is slow.

 

We don’t have a whole lot of data either.

 

I have just finished ripping some stuff out to remove some references that are getting passed around and objects created that shouldn’t be (hopefully speed a few things up).

 

Also note, I’m no dba,so it could be simple.

 

Thanks,

~David

**Comment by pezipink** [comment]
David

These queries look very simple indeed, the SQL provider will be generating SQL that is just fine here, it's a single where clause on one field.  Obviously, doing the joins client side is going to slow it down massively (can't you just join here?) - in the second query it is probably doing a full table scan to find the foodtruckid for each and every call if you don't have any indexes. The first query I will assume that is the primary key you are querying on.

However, if you don't have a huge amount of data (how much are we talking? Hundreds of rows?) you should not be seeing queries taking as long as minutes, even with a totally optimized schema - you could just pull the whole database down to the client quicker than that.

Just so we are clear here - what are the other functions you are piping into doing?  if you just call Seq.toList on the query for a single ID, how long does it take? 

(by the way, in the first query instead of using Seq.head you can write exactlyOne as the last part of the query, this will give you one result back and throw if it encounters <>1 record.)

Ross

**Comment by drcrook1** [comment]
So I performance profiled those calls.  66% of cpu is spent on Seq.head …?

 

We aren’t even at hundreds of rows, we are at like 20 rows maybe?  It’s a test database.  I was going to index the foreign keys we are using frequently.

 

The table structure looks like this:

 

CREATE TABLE [dbo].[Attendance]

(

          [Id] INT NOT NULL PRIMARY KEY IDENTITY, 

    [FoodTruckId] INT NOT NULL, 

    [OccasionId] INT NOT NULL, 

    [AttendanceStatusId] INT NOT NULL, 

    [FoodTruckRating] INT NOT NULL, 

    [OccasionRating] INT NOT NULL, 

    CONSTRAINT [FK_Attendance_AttendanceStatus] FOREIGN KEY ([AttendanceStatusId]) REFERENCES [AttendanceStatus]([Id]), 

    CONSTRAINT [FK_Attendance_FoodTruck] FOREIGN KEY ([FoodTruckId]) REFERENCES [FoodTruck]([Id]), 

    CONSTRAINT [FK_Attendance_Occasion] FOREIGN KEY ([OccasionId]) REFERENCES [Occasion]([Id])

)

 

Which immediately jumps at me as having an incorrectly defined primary key per our practices (and is also the slowest performing table).

 

I’m going to do a bit of digging real quick first and let you know how things are going.

 

Thanks,

~David

**Comment by pezipink** [comment]
David

There is something badly wrong somewhere, and I am suspecting the SQL Provider is not the cause of it.  The table definition looks ok, and you have a proper FK setup between the two tables.  For 10-20 rows it should be instant now matter how bad you write a query :)   Try a couple of things out for me 

* Attach an event handler to see the SQL it is generating  
`
FSharp.Data.Sql.Common.QueryEvents.SqlQueryEvent
|> Observable.add (printfn "%s")`

* Try pulling the whole lot down to the client and see how long it takes, without the query.  You can just use Seq.toList on [dbo].[Attendance]

As an aside, you can make the queries a lot better by just joining and getting the data all in one hit, the SQL provider will even write the join for you as you have a foreign key setup.  You should also be able to pass in a list of IDs and use the IN operator, something like this : 
```
let getFoodTruckData truckIds =
    query {for ft in context.``[DBO].[FOODTRUCK]`` do
           for sa in ft.[FK_Attendance_FoodTruck] do
           where (ft.ID |=| truckIds)
           select (ft,sa) } |> Seq.toList
```
Also note in the select satement you can directly call your conversion functions if you like.

Let me know how it goes - something strange is going on for sure!

**Comment by drcrook1** [comment]
Hi Guys,

 

So found the issue, it’s the hydration of types that takes long.  Getting the correct attendances takes <1 second as well, but to hydrate the types of an attendance, we need to make calls out to the database at least 5 times to fully hydrate all of the types involved with an attendance or an occasion.

 

Is there a way to make a call for something with foreign key relationships and get those types hydrated back to us similar to how Entity Framework does it?

 

Thanks,

~David

**Comment by pezipink** [comment]
David

It is hard to advise without seeing this other hydration code and understanding what you are doing. When you say hydration of types, are you talking about what the SQL provider is doing internally, or some extra code of your own?  What types? You still don't have a lot of data so it really should not be taking long to do stuff. 

If you have an entity, and you want to then get its children via a foreign key some time later, you can call Seq.toList (or query) directly off the property on the entity that represents the foreign key you are interested in (this is effectively then "lazy") or you can just write one query that gets all the data you need up front, an extended version of what I wrote above).

I have routinely used the SQL provider with complex data heirarchies on terrabytes of data in with no particular performance problems, so it sounds like you have at least a quadratic if not exponential problem somewhere with what you are doing here - happy to help if you can give us more info

Cheers

Ross

**Comment by drcrook1** [comment]
Hi Ross,

 

Here is what happens:

 

attendances = query {for sa in context.``[DBO].[ATTENDANCE]`` do

                                                    where (sa.OCCASIONID = id)

                                                    select sa}

                                                |> Seq.map(fun sa -> convertSqlAttendance(sa).SuccessValue)

Inside convertSQLAttendance

        let occasion = occasionRepository.Get(a.OCCASIONID)

        let foodTruck = foodTruckRepository.Get(a.FOODTRUCKID)

 

Occasion set:

                let occasion = query {for so in context.``[DBO].[OCCASION]`` do

                                        where (so.ID = id)

                                        select so}

                                        |> Seq.head

                                        |> convertSqlOccasion

Inside convert:

        let sa = streetAddressRepository.Get(so.ADDRESSID)

 

foodtruck set:

same sort of thing, except it has statuses, generators, truck types, owners, menus, inspections, window types, current alerts and payment types accepted.  This in itself blows out to like 8 calls to the database via extended queries using Seq.Map(conversion) as you can see above.

 

Summary:

I think we need to rethink our entire strategy here, but am open to hearing suggestions if you are having success with this provider on complex hierarchies against terabytes of data.  First time trying to use F# in a production code base.

 

Thanks,

~David

**Comment by drcrook1** [comment]
We may end up having to do some stored procs, can you provide a sample?  I’m not finding how to do that on your docs page.

**Comment by pezipink** [comment]
David, 

I can see why your approach is not working, this strategy is not suitable for querying data from the SQL provider (though, am still not sure why it's so slow - even though the approach is is very inefficient, SQL is lighting fast).  I do not think you will need any stored procs for this, it is very basic querying, it just needs to be written in a way that eliminates the many redundant calls that could all be done together.  All you would be doing with a sproc is exactly that - nothing that can't be replicated in the client side queries.

I am in long meetings now and won't be able to give a decent reply with e nice example until later tonight or tomorrow, unless someone beats me to it, but basically; 

* Forget the repository concept
* Query the database the least amount of times possible.  If you know you are going to need data from another 6 tables, get it all in the same query via the foreign keys (see example above)
* Where at all possible, get groups of entities at a time by passing in many IDs instead of one at a time (see example above)
* Don't select entire entities if you don't need them. It's much cheaper just to select Id, FirstName and LastName than it is to select a whole Customer (this won't work if you want to later apply updates and things, though).
* If you have some foreign keys which you don't always need, wait until you need them on an entity and then enumerate its relevant foreign key property (see example above) this will execute one query and return all the child entities related to that specific record. Note, if those new children also need to join to other data, you can do that in the same step by using a query { ... } expression over the foreign key property, and join to other tables at the same time.

As for sprocs, I rally don't think you need them, if you wanted to use sprocs you have to write and create them yourself on the sql server, then use the strored procedures property on the data context to  access them via the SQL provider.

I will show you a better example later or tomorrow

Cheers 
Ross

ps, the docs are terrible I know, am hoping to get to them soon!

**Comment by boeremak** [comment]
Isn't Seq lazily evaluated (Deferred execution) like Linq? So it goes back and forth to the DB constantly? Try a Seq.ToList() first  and list.head afterwards. Might be worth a shot.

**Comment by pezipink** [comment]
Yes, but unless the functions are being called repeatedly with the same IDs, it is still only executing them once.  The query { ... } portion over an IQueryable is what triggers the LINQ epxression tree compiler to generate SQL, then when you sometime later force it to evaluate, it will run the query and return the response - you could have chained a bunch of Seqs from that first and still nothing would have happened.

In general you are right though, with this deferred execution stuff you are better off getting the data so you know where it is up front unless you explicitly need the deferred execution.

On similar note, if you don't use query{ ... } at all and just use Seq.filter or something, it will bring the whole db down to the client and filter it there!

**Comment by drcrook1** [comment]
Ouch, not sure I want that.  I think I’m going to just write a stored procedure and call that instead of trying to figure out what this thing compiles to.

 

DO you have a sample on calling stored procs?

**Comment by colinbull** [comment]
An example of calling a stored proc, can be found here https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Tests/SqlServerTests.fsx#L167

**Comment by drcrook1** [comment]
Hi Guys,

 

Last question on this, I revamped a few queries to bring down just id’s as we didn’t need the additional data.  Queries dropped from ~10 minutes to sub seconds :)

 

The last queries that are running slow have “types” associated with them.  For example, our generator table has Propane, Diesel, Gas as the potential types, with id’s 1, 2 and 3.  A truck in the database has a FK reference to the generator it has.  Is there a way to easily bring those together?

 

Example Structure:

[dbo].[truck]

Id, Name, GeneratorId

 

[dbo].[generatortype]

Id, Name

 

Example Goal

let fullTruck = query { for truck in context.``[DBO].[TRUCK]`` do where (truck.id = id) select truck }

 

where full truck would be

{id: int; name: string; generator: Generator}

 

And Generator is a discriminated union.

 

Trucks in particular have quite a number of foreign key references to these sorts of “types” in the database.

 

Sorry if these are simple questions, I have no official training with databases.

 

Thanks,

~David

**Comment by drcrook1** [comment]
Can you guys delete the code that I sent to you via email from github?  That is from a private repository that I am working on under NDA.

 

https://github.com/fsprojects/SQLProvider/issues/130 

 

Thanks,

~David
