### ISSUE TITLE
Oracle and its special OracleDecimal

### ISSUE THREAD

**Issue by KristianSchmidt** [fsprojects/SQLProvider#159]
I just wanted to inform you that the SQLProvider is also hit by this issue:
http://stackoverflow.com/questions/26131049/how-to-use-dapper-micro-orm-with-oracle-to-map-number-oracledecimal

where ODP.NET's GetValue fails because the number in the DB is of too high precision for any of the standard .NET value types.

This is entirely Oracle's fault, and I understand if this will be marked as a wontfix, but I thought I would inform you anyway.

**Comment by colinbull** [comment]
Yes, thanks.. The issue is known and has caused a lot of swearing on my behalf. I had pretty much come to the same conclusion as that stack overflow post, and yes until Oracle, pull there finger out there isn't much we can do around this.. 

Closing for now, but will re-open if there is a valid work around.
