### ISSUE TITLE
Calling functions in query?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#177]
This is just a random thought...

- We have a [way] (http://www.fssnip.net/ts) to convert F# quotations to C# `Expression<Func<_>>`
- We have a [tool] (https://github.com/scottksmith95/LINQKit) to convert `Expression<Func<_>>` to `IQueryable<_>` from outside of DBContext. This tool is using Tomas P's old [idea](http://tomasp.net/blog/linq-expand.aspx/).
- SQLProvider executes F# query (as `IQueryable<_>`) via SQLMetal to databases

This should mean that we could quite easily combine these tools to convert F# lambda functions to SQL queries also from outside of database context `query { ... }`. Right?

With that you could do things like this (maybe with better syntax):

    let commonFilter = 
        <@ Func<_, _>(fun c ->  c.ContactName = "Matti") @> |> Lambda.toExpression

    let matti =
        query { for c in ctx.``[main].[Customers]``.AsExpandable() do
                where (commonFilter.Invoke c)
                head
        } |> Seq.toArray

...and the commonFilter is actually translated into SQL-clause.

- Would this be usefull or not? 
- Could this be used to support advanced SQL-queries without implementing the whole F# Query Expressions interface?

**Comment by pezipink** [comment]
Firstly SQLProvider does NOT use SQLMetal, that is the whole point of it. SQLMetal generates tons of code behind the scenes and only supports SQL Server.  If we were using SQLMetal would not have to implement an entire LINQ expression compiler like we currently are (which is why we don't support stuff like aggregation and nested queries, as we have not done it yet).

That aside, you may well be able to use some of this stuff to generate your IQueryable trees, as long as they are in a format which our compiler can deal with, however, most of the stuff you are looking at here can be achieved with the F# composable query project, it mostly worked with the SQLProvider anyways and @colinbull did a good bit of work to increase support for it (I think!) 

http://fsprojects.github.io/FSharp.Linq.ComposableQuery/

Cheers

**Comment by colinbull** [comment]
Yeah an example can be seen here.. https://github.com/fsprojects/SQLProvider/blob/master/tests/ComposableQueryExample/SqlProviderTest/Program.fs. However I haven't tested this for ages and it isn't a magic bullet for aggregates.

**Comment by pezipink** [comment]
No, at some point our compiler still needs to compile it :sparkles:  :)

**Comment by Thorium** [comment]
Ok, thanks, I'll have to look at those.

I think you could also already use LINQ like this for more trivial conditions:

    open System.Linq
    
    let searchCondition = (fun cs -> cs.Where(fun (c:'Entity) -> c.ContactName = "Matti"
    
    let query =  
      let beginQuery = query { for c in ctx.``[main].[Customers]`` do
                               select (c) } 
      let filterQuery:IQueryable<'Entity> = searchCondition(beginQuery)
      let selectQuery = query { for item in filterQuery do
                                head } 
      selectQuery |> Seq.toArray

**Comment by Thorium** [comment]
This wasn't actual issue, so closing this...
