### ISSUE TITLE
Return Option<T> for columns specified in a LEFT JOIN

### ISSUE THREAD

**Issue by mFingers** [fsprojects/SQLProvider#189]
I think it would be useful to return an Option for columns returned from a LEFT JOIN.  The expectation with such a query is that those values may not be there, so an option seems reasonable - particularly if `UseOptionTypes` is set to true.

Right now, I have a query where a value from the LEFT JOIN is a string, but the provider is returning an empty string instead of NULL.  In my case, an empty string shouldn't exist in the domain for that value, so I can adjust accordingly, but in general, an empty string is different from NULL (which should mean "the absence of data").

I don't mind taking a crack at this feature, if you think it seems useful.

**Comment by colinbull** [comment]
This is definitely a bug, and please yes feel free to send a PR. We should never be substituting string.empty for NULL or vice versa. 

Cheers Colin

**Comment by mFingers** [comment]
I also noticed that zero is being returned for integers and false is being returned for bools.  I'll try to get to this over the weekend.

**Comment by pezipink** [comment]
this is a bit of a weird one.  Since the SQLProvider has two modes of operation with regards to nulls - you either have the default instance of a value type (or string.empty) or you switch on option types via the static parameter.  

With left joins we are effectively making everything on the other side nullable or optional.  The overall philosophy was to never have nulls come back for anything. So to stay in line with the current design the behaviour should probably be:

1) If option types are off, then null columns from the joined table are represented by the default value (which is what is happening now I guess)
2) If option types are on, then all columns from the joined table should be option types whether the column itself is nullable or not

I realise though that 1) is a bit weird in the case of the join, I think it may be reasonable to simply always make left joined tables columns to be option types regardless of the static parameter.  Open to discussion on this what do you think?

**Comment by mFingers** [comment]
There might be a larger discussion looming here.  I do think it can be misleading to turn database NULL values into real values:  zero, false, and an empty string are "some data", but a database NULL means "no data".  I'm sure there are use cases for setting UseOptionTypes to false, but it seems like a practice that could generate some hard to find bugs.

It might be best to table that specific conversation, but go ahead and fix what looks like a bug with the LEFT JOINED columns that are NULL being set to their default value when UseOptionTypes is true.

I do think it would be confusing to a user if they have UseOptionTypes set to false, but then have LEFT JOINED columns get returned as options, so I would leave that behavior as it currently is.

**Comment by pezipink** [comment]
You are right it can be, though I do explictly mention this somewhere as something to watch out for if you need to distinguish between 0 and null.  Option types are a bit of a pain and a lot of the time you don't need to care which is why I decided to not force them on the user, with that caveat.

I agree with your suggestion to just fix the columns incorrectly appearing as 0 rather than None if option types are on, I was not sure if you were saying it happens with the option types or not. Some(0) is certainly wrong and needs fixing!

Ross
