### ISSUE TITLE
Dynamic connectionstring

### ISSUE THREAD

**Issue by nojaf** [fsprojects/SQLProvider#192]
I'm new to F# and I'm trying to setup a connection for a MS SQL Server.
I only know my connection string at runtime and I'm not sure what's wrong with this.

```F#
    type ConnectionStringValue = ConnectionStringValue of string
    let readConnectionString ():ConnectionStringValue =
        let json = System.IO.File.ReadAllText("config.json");
        let config = JsonValue.Parse(json);
        ConnectionStringValue(sprintf "server=%s;Integrated Security=SSPI;database=%s;pooling=true" (config?server.AsString()) (config?database.AsString()))

    
    let conn:string = readConnectionString().ToString();
    type database = SqlDataProvider<
                        ConnectionString = conn,
                        DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER>
```

I get an error on ```conn``` saying 

> This is not a valid constant expression or custom attribute value

What am I missing here?

**Comment by pezipink** [comment]
Hello, for the connection string, the static parameter MUST be a literal string known at compile time (this can be a `[<Literal>]` F# string or a named connection string read from the app.config).  Since the type provider is executing at compile time, it needs to be able to generate the type system for you as you are working on the program, and it does this by reading the database schema.

You can pass a runtime connection string as well - there is an overload on the `GetDataContext` method that accepts any runtime string. Obviously, the runtime database schema will need to match the one you were compiling against.

**Comment by nojaf** [comment]
Worked, thanks!
