### ISSUE TITLE
Unit tests are in ignore?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#195]
What is wrong with unit tests?
They are in ignore: `[<Test; Ignore("Not Supported")>]`

1) FSharp.Data and Fake packages are not used in the test project so these should be removed from tests/SqlProvider.Tests/paket.references

2) After some merges we losed the ability to have Unix style path separator character in Windows so this won't work anymore:

	[<Literal>]
	let connectionString = @"Data Source=./db/northwindEF.db;Version=3;Read Only=false;FailIfMissing=True;"

If we want to Support also Mono, then this should be fixed, shouldn't be too hard. But if we want to just debug the tests then you can replace the database with `.\db\northwindEF.db` and we get to the next problem...

3) Seems like `System.Data.SQLite.dll` is not enough for SQLite, it also uses `SQLite.Interop.dll`
But it seems to fail now. I don't know why but it could be that it is using the X86 version when it should load the X64 on new machines. But what determines the path?

Maybe something like this is needed to somewhere:

    open System.Runtime.InteropServices
    open System.IO

    module NativeMethods =
        [<DllImport(@"kernel32.dll", CallingConvention = CallingConvention.Cdecl)>]
        extern bool SetDllDirectory(string pathName)

    #if INTERACTIVE
    let path = Path.Combine [|__SOURCE_DIRECTORY__; "bin"; "Debug" |]
    #else
    let path = System.Reflection.Assembly.GetExecutingAssembly().Location
               |> System.IO.Path.GetDirectoryName
    #endif

    let interopPath =
        match Environment.Is64BitProcess with // or: if(IntPtr.Size == 8)
        | true -> Path.Combine [|path; "X64"|]
        | false -> Path.Combine [|path; "X86"|]

    NativeMethods.SetDllDirectory(interopPath) |> ignore

But I'm bit lost here, so I'm not sure.

**Comment by mFingers** [comment]
From what I can tell, the tests that are ignored as "Not Supported" are simply placeholders for future work (kind of a "TO DO" list).

If you run the tests from the FAKE script: `build RunTests`, everything works just fine.  I found the problems you mention above (1 and 2) when trying to compile through Visual Studio.  I got past that doing the same things you mentioned.  I tried to get the tests to load in the Test Explorer by adding the [NUnitTestAdapter](http://www.nuget.org/packages/NUnitTestAdapter/2.0.0), but I couldn't get them to show up....

I am interested in understanding the tests, too.  I hate mincing words, but I would consider the current tests more like integration tests than unit tests, since they test the external aspects of the provider.  That is very useful (and necessary!), but I would like to know if there is a strategy to test the internals of the provider as well?  As somebody who wants to contribute, I would love to have more tests there so that I can be more confident in the changes I make.  I'm happy to help formulate that strategy, but being what I consider an "advanced beginner" in F#, and for all practical purposes, no knowledge on how to write a type provider, I would need guidance.

**Comment by mFingers** [comment]
To clarify what I was thinking regarding testing internals, please check out [this gist](https://gist.github.com/mFingers/3d33b055dbcc5fdd5407).

**Comment by pezipink** [comment]
Yeah those tests are marked as ignore simply so they don't run as part of the build, this is because it is very hard to actually have a database available and ready at a path we expect (both at compile at runtime) that will work with the CI builds. I did put a lot of effort into getting it to work with SQLite but we had a load of problems and gave up.  I believe @colinbull has done some good work at getting some docker images up and creating databases so we can run those tests but that work is not done yet.

You are right in these tests are (sort of) more integration tests, the reason for this is that type provider internals in general are very difficult to behavior test.  This is for various tricky reasons that some can be got around but it is generally quite a pain.

I looked at your gist, it makes sense what you want to do, the problem is that the record type and dictionary is populated by our linq expression tree compiler which in turn is fed by expression trees internally by the f# compiler from `query` blocks. The underlying linq expression gets triggered at runtime and calls the `CreateQuery` methods on the linq interfaces, this is not in our control - whilst there are probably some secret trapdoors to get us in there, (I can't remember now, it was years ago) it is a pain and the easier option is to simply assert the results of the queries are correct rather than the generated sql is correct.

The other option of course is to populate those types manually, doing so requires fairly intimate knowledge of the various silly things linq does and how we compile those out - either that or simply look at what a given query looks like at the stage just before `GenerateQueryText` is called and manually re-create it in a test.

The problem in general here is LINQ in a type provider - it is a beast, if you want to know more about the architecture please watch my talk https://www.youtube.com/watch?v=PrmF6a0iTXk

I do of course agree it would be nice to test some of that stuff, if you want to have a go please be my guest :+1:

**Comment by Thorium** [comment]
Unit tests are back, on some level.
They are working on AppVeyor and local builds but disabled in Travis (Mono).
Some operators are still in not "Not Supported":

- Last. But what is the point of `last` when you can do `sortByDescending` and `head`.
- Contains and exists. But what is the point of those when you can do in-clause and like '%%' with custom operators `|=|` and `%=`

**Comment by colinbull** [comment]
Those test are there to show the coverage of the season provider in terms of what is documented in th f# query expression documentation. There may well be be an overlap / duplicates in places..
