### ISSUE TITLE
PostgreSQL: Can select, but unable to insert

### ISSUE THREAD

**Issue by nerfpops** [fsprojects/SQLProvider#249]
### Description

Receives this exception when trying to insert:

    Unhandled Exception:
    System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
      at System.ThrowHelper.ThrowKeyNotFoundException () <0x7f4b24cb7080 + 0x00015> in <filename unknown>:0

[Entire stack trace](http://pastebin.com/GA9cyKka)

I've tried the latest Npgsql 3.1.0 alpha and current 3.0.5. With v. 3* i can compile and the exception happens at runtime on SubmitUpdates (I think, have yet to get to the point where I can debug in VS Code). When using Npsql 2.2.7 the exception is caught at compiletime and SqlDataProvider is marked as the offender, and I have no clue what to do here either. I can select data with Npgsql 3*.

### Repro steps

Please provide the steps required to reproduce the problem

1. Postgres: create table test (hesting int);

2. [Run this](http://pastebin.com/4Vc0Dsg6)

### Related information 

There's other issues suggesting that PostgreSQL case sensitivity might be the problem here. Tried building from source but [this recently merged patch](https://github.com/fsprojects/SQLProvider/pull/210) didn't seem to do any difference.

* Xubuntu 15.10
* Branch: Both NuGet package and master
* Mono 4.2.3
* Npgsql 2 and 3
* PostgreSQL 9.5.2

**Comment by mariomeyrelles** [comment]
To be very honest, I had the same problem. The problem was, indeed, the case sensitivity of PostgreSQL. To fix this, I renamed the columns of to lower case. If you create the table using the UI (pgAdmin) and use Pascal case to name the columns, the are created , for example, like "Id" instead of id. When the names are double quoted in PostgreSQL, the case sensitivity is turned on. This is why you can't insert the data. 

This is a lesson learned for me and for all reading this, please, use all columns in lower case and be sure to avoid double quotes on column names.

**Comment by nerfpops** [comment]
All my columns are lowercase. I tried setting the case sensitivity when initializing SqlDataProvider to tolower, toupper and original but without luck

**Comment by Thorium** [comment]
Did you have a primary key in your table?

**Comment by nerfpops** [comment]
No primary key. I tested with `create table test (hesting int);`

**Comment by Thorium** [comment]
Ok so this is related to #265
