### ISSUE TITLE
Can't use Mysql.Data 7.0.3-DMR

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/SQLProvider#302]
Hello  guys.

### Description

I just started a new project with SQLProvider and so I installed in a greedy manner Mysql.Data 7.0.3-DMR, and I got an error: 

`cannot load one or several types` 

when trying to declare the `SqlDataProvider` type:

```fsharp
type sql = SqlDataProvider<
                dbVendor,
                connString,
                ResolutionPath = resPath,
                IndividualsAmount = indivAmount,
                UseOptionTypes = useOptTypes,
                Owner = "pocAdmin"
                >
```

When I switch back to Mysql.Data 6.9.9 everything is fine. It's probably a problem from the pre-release version of Mysql.Data but probably good to check out the reason :).

### Related information 

* Windows 7 Enterprise x64
* Nuget version 1.0.22
* .NET Runtime 4.5

**Comment by Thorium** [comment]
The reason is that Mysql.Data 7.0.3-DMR has internal reference to Google.ProtocolBuffers.dll which is not contained in the package itself.

The error message was unclear so I fixed that.

Now, if you reference the Google.ProtocolBuffers Nuget package (copy the Google.ProtocolBuffers.dll to the location where it can be found, and restart Visual Studio), the system works fine with the new dll also.

**Comment by MangelMaxime** [comment]
Thanks for the answer :)
