### ISSUE TITLE
Some System.Linq.Expressions parsing development ideas

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#323]
First of all, I think we should override our expression tree parsing to detect Invoke() call to type of our SqlProvider. Then we could parse our nested lambdas in one place and not one-by-one from the projections. Something like this will be needed to our GroupBy: We can't execute the SQL-clauses on each select of inner whatever grouping, we will need to make the whole expression tree once and after that execute the SQL-clause.

Second, simplification of expression trees could be useful. I don't want to call `Compile().Invoke()`, just a simple things described below. I googled a simple lightweight System.Linq.Expression optimizer but surprisingly enough couldn't find any useful. There is the Nessos optimizer which has a different point of view. Although they had one good idea:

1. Purge anonumous types / tuples to function parameters. 
   - If we would copy the idea of this, it would be much easier for us to handle complex joins, grouping and selects, because currently the items look like this: `new Anonymous(Item1=cust, item2=cust.Country)` and the next lambda says take just `Item1.City` and these would be enough but as we evaluate these separately we just have to take the whole cust object to select1.

And then few more that came in to my mind:

Let's say that there is a business logics heavily related to database:

```fsharp
[<Test >]
let ``simple select with bool outside query``() = 
    let dc = sql.GetDataContext()
    let rnd = System.Random()
    // Direct items outside LINQ:
    let caseContactEnum = rnd.Next(3)
    let myCond1 = rnd.NextDouble() > 0.5
    let myCond2 = rnd.NextDouble()

    let myBusinessLogics = 
        query {
            for cust in dc.Main.Customers do
            where ((myCond1 && myCond2 < 0.5) || ((myCond2 < 0.5) && cust.City="London"))
            select (
                if caseContactEnum=1 then 
                    cust.ContactName 
                else if caseContactEnum=2 then
                    cust.Address
                else cust.CompanyName)
        } |> Seq.toArray
    
    CollectionAssert.IsNotEmpty myBusinessLogics
```
Now, there is (in here) two places of parsing System.Linq.Expression expression-trees: where and select. (Actually in SQLProvider code I think Select is currently doing better and where could be refactored to use that. ) The thing is that these variables outside the SQL properties are ConstantExpressions for the expression and could be parsed and simplified already before creating the SQL.

I would also like to have these optimizations, but actually optimization shouldn't happen in `SqlRuntime.QueryExpression.fs` which is complex enough already. 

2. Purge constant expressions: `myCond2 < 0.5` is BinaryExpression of ExpressionType.LessThan and inside that two ConstantExpression having value, so that can be simply reduced to ConstantExpression of bool true or false.

3. Simple Boolean algebra reducing, e.g. deMorgan. This should be fairy trivial. Maybe something like this: http://www.fssnip.net/7QB

4. If you have a huge list of AND-conditions or OR-conditions when constructing the expression tree:

```
AND(AND(AND(AND(AND(AND(AND(AND(AND(AND(A, B), C), E), F), G) H), I), J), K), L)
```
this will cause unnecessary stackoverflow exception when walking the expression-tree and also very slow SQL-execution. So I would just like to balance this to a binary tree. There is a lot smaller stack ("amount of nested parentheses"):

```
AND((AND(A, B), AND(C, D)) AND (AND(E, F), AND(G, H))), (AND(I, J), AND(K, L)))
```
Kind of what this is doing: https://github.com/scottksmith95/LINQKit/blob/96626e863784bac5d324c5cb4b189f5cb902d1ab/src/LinqKit/AggregateBalanced.cs

**Comment by ingted** [comment]
Hi Thorium,

Excuse me, just curious, why we choose Linq Expression but not Quotation to build the parser?
(PS. I am not computer science background, so I want to learn about this from you^^)

**Comment by Thorium** [comment]
Well, @pezipink can answer about the the initial decisions... ;-) 

But I'm kind of happy to the marketing phrase "LINQ supported" here: You can say that in theory we could operate with C# LINQ queries, or transfer the queries back and forth, and LINQ abstraction over SQL databases are fairly well tested with EntityFramework. Of course in practice no-one would like to try to use C#.

**Comment by pezipink** [comment]
The initial work on the SQLProvider was based directly off the XRM LINQ type provider that I wrote whilst I was working at Microsoft Research.

Because of this there are several things that don't really belong in the SQL TP that got carried over.  As for LINQ itself, in retrospect it would have been way better to either A) support quoted F#  code as suggested above or B) write our own computation expression instead of using `query`, since that is completely out of our control, and to conform to the C#/VB standard, the F# compiler has to do all kinds of strange and unpredictable things with LINQ expression trees that we would be able to avoid completely.

However, since I wrote this on my own initially and even using the XRM type provider as a base, it was a huge amount of work and I simply wouldn't have done it if I went down the route of A) or B) !

@Thorium I am all for improving the LINQ stuff, but if significant time is to be invested I would perhaps suggest we go for B) instead since it will put everything under our control and avoid a great deal of the problems that we have to deal with using LINQ.  As you say, whilst it's a nice selling point on paper, in reality no one uses it for being able to pass IQueryable things around to other things.

**Comment by Thorium** [comment]
well, at least for junior-F# developers it's nice that you can say `open System.Linq` and write your query with familiar C#-syntax. I don't see the benefit of quite large refactoring away from LINQ now that it's working quite well.

**Comment by pezipink** [comment]
Yeah, I wouldn't suggest refactoring. Since the architecture is that of a simple compiler, with a front end and multiple backends, it is relatively simple to add other front ends to it as well whilst retaining what we already have.

Our own CE would give us a great deal more power, but it would indeed be a large amount of work.

However, at least the option for writing other front ends is there for the adventurous, brave, silly , or simply someone with way too much time on their hands who likes a challenging problem! :)

**Comment by Thorium** [comment]
Some of the things I mentioned in the first post are in this commit: #325
