### ISSUE TITLE
Dacpac or sqlproj project?

### ISSUE THREAD

**Issue by davidtme** [fsprojects/SQLProvider#361]
Would it be possible to create a provider that uses a dacpac file or better still a sqlproj project to create/update the schema/types but then uses the MsSqlServer provider for querying?

**Comment by Thorium** [comment]
I can't see why not as long as you have an development/build environment running a database... Do you want describe more if there is a problem?

**Comment by davidtme** [comment]
Ideally I would like the following - which I guess would mean the development environment doesn't use the database:

Have a SQL Server Project (.sqlproj) that the type provider reads the database schema from there and build the types around this, meaning I can quickly add new tables and code with them without having deploy the dacpac or get a database involved. At runtime I will deploy the dacpac so the database is ready to for the type provider to query.

(Please forgive me if I’m completely wrong about this) I’m also thinking about build servers - if someone changes the sqlproj/dacpac without changing the fsharp code it will inform us if there is a mismatch.

**Comment by pezipink** [comment]
This sounds like am interesting idea for when we finally get around to an offline-caching solution.  I don't know if they standardized the dacpac stuff yet, but assuming that is not the case, each db provider would need to supply its own implementation for reading (and possibly writing) the dacpac into a general form of some kind. Oracle in particular supports things like Packages which are unique to it (I believe)

If we can not easily write the dacpacs then it would decrease the ability for the sqlprovider to "just work" without messing around creating dacpacs from .sqlproject or equivalent, since in a lot of cases that simply won't exist.

**Comment by simonhdickson** [comment]
I might actually take on this task, there is a DAC API so it may not be such a huge feat in reality:

https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.dac.aspx

**Comment by Thorium** [comment]
Supported in the latest release by PR #704
