### ISSUE TITLE
Using MSSQLSERVER does not populate VS Intellisense after calling GetDataContext() 

### ISSUE THREAD

**Issue by jenaewhitmore** [fsprojects/SQLProvider#374]
### Description

Following the steps as listed on the Documentation site does not populate properly.

### Repro steps

Please provide the steps required to reproduce the problem

Code to connect:
```
let [<Literal>] dbVendor = Common.DatabaseProviderTypes.MSSQLSERVER
let [<Literal>] connString = "Server=server\instance;Database=databaseTest;User ID=user;Password=password"
let [<Literal>] tableNames = "hsi.test"
let [<Literal>] resPath = "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies"
```

```
type sql =  SqlDataProvider<dbVendor,
                            connString, 
                            ResolutionPath = resPath,
                            TableNames = tableNames>

let test = sql.GetDataContext()
```

### Expected behavior

when accessing test, the column names should be available from hsi.test via intellisense. There are no errors on build or otherwise.

### Actual behavior
The only options are 
```
ClearUpdates
CreateConnection
GetUpdates
PossibleError
Procedures
SubmitUpdates
SubmitUpdatesAsync
```

### Related information 

SqlServer 2014
Windows 8.1 x64
Using SqlServer Authentication

**Comment by pezipink** [comment]
Hello, the tableNames parameter is used as a white-list for databases with excessively sized schemas. This is a literal string, not a file.

`a comma separated table names list to limit a number of tables in big instances. The names can have '%' sign to handle it as in the 'LIKE' query (Oracle and MSSQL Only)`

You do not need to supply a resolution path for SQL Sever since it is built into ADO.NET.

If you remove the resolution path and the table names parameters you should be fine.

**Comment by jenaewhitmore** [comment]
And that was the case! Thanks so much.
