### ISSUE TITLE
Error Mapping SqlDbType Time

### ISSUE THREAD

**Issue by matthewblott** [fsprojects/SQLProvider#521]
### Description

I'm unable to build a project referencing FSharp.Data.SqlProvider using ```dotnet build```. The provider does it's work and 'logs in' (i.e. if I use an invalid connection string this gets reported) but I'm informed there's an error with 'mapping'.

### Repro steps

Please provide the steps required to reproduce the problem

1. Created a simple F# console project from the command line.

2. Installed SQLProvider via nuget.

### Expected behavior

Project should build successfully.

### Actual behavior

The following error is reported ....

```
The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: No mapping exists from SqlDbType Time to a known DbType.Parameter name: SqlDbType
```

### Known workarounds

None

### Related information 

* SQL Express on Linux
* macOS
* .NET Core 2.0
* Performance information, links to performance testing scripts

**Comment by Thorium** [comment]
I think this has been working before. Could #516 have broken it?

**Comment by matthewblott** [comment]
I did suspect it might be something to do with using a later version of SQL Server. FWIW I created a blank database with no objects created to test on but still got the error. The code is very simple ...

```
let [<Literal>] ConnString = "server=ubuntu16;database=matt;user id=matt;password=password"
let [<Literal>] DbVendor = Common.DatabaseProviderTypes.MSSQLSERVER
let [<Literal>] IndivAmount = 1000

let [<Literal>] UseOptTypes  = false

type Db =
  SqlDataProvider<DbVendor, ConnString, IndividualsAmount = IndivAmount,UseOptionTypes = UseOptTypes>

let ctx = Db.GetDataContext()

```

**Comment by Thorium** [comment]
If you are using NuGet can you try the version 1.1.31, just to see is that about it?

**Comment by matthewblott** [comment]
That works 👍 Thanks :-)

**Comment by Thorium** [comment]
Ok we have to get this to work also with the new version.

What is your SQL Server productversion and database compatibility_level ?

```sql
select @@version, SERVERPROPERTY ('productversion');
SELECT name , compatibility_level FROM sys.databases;
```

**Comment by matthewblott** [comment]
Microsoft SQL Server 2017 (RTM-CU1) (KB4038634) - 14.0.3006.16 (X64) 
  Oct 19 2017 02:42:29 
  Copyright (C) 2017 Microsoft Corporation
  Developer Edition (64-bit) on Linux (Ubuntu 16.04.2 LTS)

**Comment by matthewblott** [comment]
Hmm, unfortunately we've still got issues. It compiles fine now but it complains about a missing assembly at runtime ...

```
he type initializer for '<StartupCode$app1>.$Data' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

```

That version of ```System.Data.SqlClient``` doesn't exist as far as I know (I can't see it on nuget and it doesn't install on my attempt).

**Comment by matthewblott** [comment]
Mybad - ignore previous comment (I was doing a post build copy which imported the wrong file!).

**Comment by michal-duda** [comment]
@matthewblott this is weird I have no issue with version 14.0.1000.169. Time column should be supported since 2008.  When you run 

    select * from sys.systypes where name='time'

Does it normally return time type?

**Comment by matthewblott** [comment]
Yep ...

![s 2018-02-25 at 21 46 23](https://user-images.githubusercontent.com/1231417/36646867-6218a2d2-1a75-11e8-9c9f-86782682451c.jpg)

**Comment by piaste** [comment]
Ok, I encountered this issue too now and figured it out.

 - It's a bug in Mono, up to at least 5.8.0.108
 - It's fixed in Mono v5.10 (tested with 5.10.0.160)

Personally I only use Mono in the build server docker image, so I'm OK with documenting 5.10 as the minimum supported version and moving on.

**Comment by juselius** [comment]
Any progress on this issue? 

I just tested, and every version of SQLProvider > 1.1.31 is broken under mono:
```
error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: No mapping exists from SqlDbType Time to a known DbType.Parameter name: SqlDbType
```
I have tested with:
* mono 5.8.0.108 and 5.14.0.177
* dotnet 2.1.301 and 2.1.400
* Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64)  Linux

**Comment by piaste** [comment]
@juselius

Can you determine which version of `System.Data` you are using at compile time?
Could you try taking the most recent version that ships with mono, and copying it into your `ResolutionPath`?

**Comment by juselius** [comment]
@piaste unfortunately that didn't work either. I'm giving up. SQLProvider + .NET Core + Linux is a total shit show. I can't even get the SQLProvider.Core.Tests examples to work. They fail with the usual: ``error FS3033 : The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error : The method or operation is not implemented.``

**Comment by juselius** [comment]
I finally managed to get it to work. One must use Npgsql 3.2.5 and System.Threading.Task.Extensions 4.4.0, otherwise things break badly.

I have created a Gist with a minimal .fsproj file for future reference: https://gist.github.com/juselius/c074bf06facf66ff4167ad69bac8f980

The whole thing hinges on getting the dependencies right, which is non-trivial, since the errors you get from SQLProvider are pretty much useless. Using Npgsql > 3.2.5 does not work: Npgsql 3.2.7 causes mono to sigsegv, and Npgsql 4.0.* dependes on System.Threading.Task.Extensions > 4.5, which causes endless, confusing errors. 

I'm wondering if it would have been a wiser solution to create one .dll and NuGet package per supported database, instead of trying to support everything through reflection. That way each provider would come with the correct dependencies, and the compiler could probably produce more sensible errors when things go tits up. Any thoughts on this? @Thorium?
