### ISSUE TITLE
groupBy across different tables

### ISSUE THREAD

**Issue by joelluijmes** [fsprojects/SQLProvider#527]
Hey I wanted to write a query which groups by on multiple columns. As per #358 groupby has been added for a single column, are there any plans to extend this feature for multiple columns?

**Comment by Thorium** [comment]
I think it works on multiple columns but single table only...?

**Comment by joelluijmes** [comment]
Yes you're right, it works with multiple columns on single table. However I was looking for a group by across different tables.
Would it be possible to add that? 

_As a workaround I currently created a view on the database which does that._

**Comment by Thorium** [comment]
Yes, this is quite large item, because the next thing you want to do is nested selects over the groupbys, something like this:

```sql
select u.name, u.email, invoicingsum, ordersum
from users u
left join (
	select i.UserId, sum(sum) as invoicingsum 
	from invoices i
	group by i.UserId
) as i on u.Id=i.UserId
join (
	select o.UserId, sum(sum) as ordersum
	from orders o
	group by o.UserId
) as o on u.Id=o.UserId
```

This will involve some complex LINQ-lambda-projection-parsing.

...and then soon you are in EntityFramework-style problems where you auto-generate 2000 lines of SQL which performance is hard to monitor and your DBA hates you. 

We can try to move to that direction, but it'll take time. I think @pezipink never intended SQLProvider to be a fsharp-to-sql compiler.

The current workaround/approach is that you do 90% of your database queries with SQLProvider and for the complex 10% of queries you create a view to the database. The view (and procedures) can be used with SQLProvider.

**Comment by Thorium** [comment]
With the latest 1.1.72 version you can do simple join-groupby like this:
```fsharp
    let qry = 
        query {
                for cust in dc.Main.Customers do
                join order in dc.Main.Orders on (cust.CustomerId = order.CustomerId)
                groupBy cust.City into g
                select (g.Key, g.Count())
            }
    let res = qry |> dict  
```

...or bit more complex like this:

```fsharp
    let qry = 
        query {
                for cust in dc.Main.Customers do
                join order in dc.Main.Orders on (cust.CustomerId = order.CustomerId)
                groupBy (cust.City, order.ShipCity) into g
                select (g.Key, g.Max(fun (c,o) -> c.PostalCode))
            }
    let res = qry |> dict  
```
