### ISSUE TITLE
Attaching entity to another context / updating single field

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#561]
I have a business need to do the following and I was thinking is this a common use case, so should I include a solution to SQLProvider. So what are your views: what kind of user interface would be good for the developer?

1. I have a large database table with many varchar(max) columns. I want to update a single small column. I know the primary key. I don't want to fetch the whole entity. Almost like individuals, but dynamic individual. For example, something like this could do:

```fsharp
let isOk = ctx.myTable.ItemHavingKey(432).Email <- "tuomas@mailinator.com"
```

2. I have a web-service call and I don't want to span the transaction over that. So I'll fetch some data from context 1 and then do the call and save the result to context 2. The entity I got from context 1 doesn't get saved when I save the context 2. So I should have a method to attach/copy the entity to another context.

```fsharp
let doAll() =
   let myItem = 
       let ctx1 = HR.GetDataContext()
       let item = query { for x in ctx1.MyTable.Item do select x} |> Seq.head
       item.callTime <- DateTime.Now 
       ctx1.SubmitUpdates()   
       item // return so ctx1 closes here but item lives! 
   let someActionResult = 
       myWebServiceCall(myItem.firstname) // takes e.g 1 minute
   let saved =
       let ctx2 = HR.GetDataContext()
       myItem.wsResult <- someActionResult
       ctx2.AttachItem(myItem)   
       ctx2.SubmitUpdates()   
   saved
```

What you think?
These could be quite easy to implement using current entities code.

**Comment by piaste** [comment]
(1) could be really useful. Would it be feasible to instead add a custom `update` LINQ keyword? Since in SQL, or at least in the subset of SQL we generate, everything after 'from' stays the same for both update and select queries, I think the amount of work wouldn't be too far off, and it would be far more powerful as we could generate arbitrary update statements. Also it would be less of a special-case addition.

(2) seems fine, I don't like the 'AttachItem' name much though - it's a bit implementation-detail-y, and also it looks out of place with the other methods. How about `AddUpdates` or `ImportUpdates`?

Also, what happens if I attach an item from database A to a context in database B? I doubt it can be made into a compile-timer error (though it would be nice), but we should make sure it throws an exception _immediately_ instead of running commands on the wrong databaase.

**Comment by Thorium** [comment]
(1) Currently I'm using @pezipink's great idea to just create a new entity and modify the _state:
```fsharp
let ``update myTable fields`` entityId colValues =
        async {
            let newItem = dbContext.dbo.MyTable.Create()
            newItem.Id <- entityId
            colValues |> List.iter(fun (columnName, columnValue) ->
                do newItem.SetColumn<string>(columnName, columnValue)
            )
            newItem._State <- Common.EntityState.Modified (colValues |> List.map fst)
            do! dbContext.SubmitUpdates2()
        }
```
This generates SQL like this:  `update myTable set colum=@param1 where id=@id` leaving all the other columns un-touched. But I was thinking should it be added to SQL-provider for entity properties like there is now the `.Clone()` which duplicates a database row.

(2) Each entity is basically a dictionary at runtime. The idea was just copy the internal dictionary to another context's object. So it doesn't really matter if the database changes as long as the shape of the entity is the same.
