### ISSUE TITLE
Individuals field doesn't get serialized when saving the context on SQLite

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/SQLProvider#770]
**Describe the bug**
When context schema is generated, the individuals field doesn't get serialize even before hand I access to some individuals on the code

**To Reproduce**

I access to some individuals data as in
```fsharp
let offsetCount =   ctx.Main.Offsets.Individuals.Visitors.OffsetCount
```

Right after that

I do create the schema by typing
```fsharp
 ctx.``Design Time Commands``.SaveContextSchema.``Saved /Users/onur/Repos/BinPacker/src/Query/../Server/Database/Schema.sqlite at 05:03:08``
```

Then I can see the schema file is created all the details except the  individuals field is empty.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/4114592/196213515-1cc0a25c-ab99-4158-b6f1-538d6c7bc4dc.png">

**Expected behavior**
I would expect individuals field to be filled

**Desktop (please complete the following information):**
 - OS: Macos

Using Latest SqlProvider against SQLite on .NET 6.0.400 SDK

**Comment by OnurGumus** [comment]
Hello @Thorium, is this known to be working or any directions? Otherwise this effectively makes individuals useless.

**Comment by OnurGumus** [comment]
Thanks for the response. When I look at the code here 
https://github.com/fsprojects/SQLProvider/blob/cc1275f26ba689b1901ae0cee9661612a116050d/src/SQLProvider.DesignTime/SqlDesignTime.fs#L201

Individuals appear to be added to the schema cache. I wonder what prevents them to be serialized.

**Comment by Thorium** [comment]
Fixed, however I'm not very happy that Individuals combined with SchemaContextPath may save some sensitive data to un-encrypted JSON file, if someone develops against a production database. Luckily many ifs and Individuals are erased with compile time. 

The other problem is that schema file may grow fast, because it's loading on "Individuals" call the first X items from that table, not only the used item. I dropped the default 1000 to 50, but it's a parameter so if you want huge schemas you can.

**Comment by OnurGumus** [comment]
oh I need to test this immediately :) awesome and your points are valid. Will give feedback

**Comment by OnurGumus** [comment]
Tested and works great, thanks!
